-- ==============================================================================
-- Populate the Class_Catalog Table
-- Extracted from GSU CSC Graduate Catalog (Raw Text Verification)
-- ==============================================================================

INSERT INTO Class_Catalog (class_prefix, graduate_class_number, class_title, credits) VALUES
('MATH', '2211', 'Calculus of One Variable I', 4),
('MATH', '2212', 'Calculus of One Variable II', 4),
('CSC', '2510', 'Theoretical Foundations of Computer Science', 3),
('CSC', '2720', 'Data Structures', 3),
('CSC', '3210', 'Computer Organization and Programming', 3),
('CSC', '6030', 'Computational Epidemiology I', 4),
('CSC', '6040', 'Computational Epidemiology II', 4),
('CSC', '6110', 'Introduction to Embedded Systems Laboratory', 4),
('CSC', '6120', 'Introduction to Robotics', 4),
('CSC', '6210', 'Computer Architecture', 4),
('CSC', '6220', 'Computer Networks', 4),
('CSC', '6221', 'Mobile Computing and Wireless Network Security', 4),
('CSC', '6222', 'Fundamentals of Cybersecurity', 4),
('CSC', '6223', 'Privacy', 4),
('CSC', '6224', 'Ethical Hacking', 4),
('CSC', '6225', 'Internetwork Programming', 4),
('CSC', '6226', 'Secure Software Engineering', 4),
('CSC', '6227', 'Network Security', 4),
('CSC', '6250', 'Malware Analysis and Defense', 4),
('CSC', '6251', 'Computer Forensics', 4),
('CSC', '6260', 'Digital Image Processing', 4),
('CSC', '6270', 'Digital Signal Processing', 4),
('CSC', '6310', 'Parallel and Distributed Computing', 4),
('CSC', '6311', 'Cloud Computing', 4),
('CSC', '6320', 'Operating Systems', 4),
('CSC', '6330', 'Programming Language Concepts', 4),
('CSC', '6340', 'Compilers', 4),
('CSC', '6350', 'Software Engineering', 4),
('CSC', '6360', 'Mobile Application Development', 4),
('CSC', '6370', 'Web Programming', 4),
('CSC', '6380', 'Windowing Systems Programming', 4),
('CSC', '6510', 'Automata', 4),
('CSC', '6520', 'Design and Analysis of Algorithms', 4),
('CSC', '6610', 'Numerical Analysis I', 4),
('CSC', '6620', 'Numerical Analysis II', 4),
('CSC', '6630', 'Matlab', 4),
('CSC', '6640', 'Fundamentals of Bioinformatics', 4),
('CSC', '6650', 'Introduction to Bioinformatics', 4),
('CSC', '6710', 'Database Systems', 4),
('CSC', '6720', 'Human-Computer Interaction', 4),
('CSC', '6730', 'Data Visualization', 4),
('CSC', '6740', 'Data Mining', 4),
('CSC', '6741', 'Data Mining for Analytics', 4),
('CSC', '6750', 'Semantic Web', 4),
('CSC', '6760', 'Big Data Programming', 4),
('CSC', '6780', 'Fundamentals of Data Science', 4),
('CSC', '6810', 'Artificial Intelligence', 4),
('CSC', '6820', 'Interactive Computer Graphics', 4),
('CSC', '6821', 'Fundamentals of Game Design', 4),
('CSC', '6840', 'Advanced Computer Graphics Programming', 4),
('CSC', '6841', 'Computer Animation', 4),
('CSC', '6850', 'Machine Learning', 4),
('CSC', '6851', 'Introduction to Deep Learning', 4),
('CSC', '6980', 'Topics in Computer Science', 4),
('CSC', '7003', 'Programming for Data Science', 4),
('CSC', '7350', 'Programming for Bioinformatics', 4),
('CSC', '7351', 'Systems Programming for Bioinformatics', 4),
('CSC', '7352', 'Advanced Programming for Bioinformatics', 4),
('CSC', '7850', 'Machine Learning-TAIS', 4),
('CSC', '7851', 'Deep Learning-TAIS', 4),
('CSC', '7950', 'Secure Artificial Intelligence-TAIS', 4),
('CSC', '7951', 'Private Artificial Intelligence-TAIS', 4),
('CSC', '8050', 'Statistics for Bioinformatics', 4),
('CSC', '8210', 'Advanced Computer Architecture', 4),
('CSC', '8220', 'Advanced Computer Networks', 4),
('CSC', '8221', 'Optical and Wireless Networks', 4),
('CSC', '8222', 'Network Security', 4),
('CSC', '8223', 'Internet of Things', 4),
('CSC', '8224', 'Cryptography', 4),
('CSC', '8228', 'Privacy Aware Computing', 4),
('CSC', '8230', 'Secure and Private Artificial Intelligence', 4),
('CSC', '8250', 'Advanced Digital Signal Processing', 4),
('CSC', '8251', 'Sensor Web Architecture and Protocols', 4),
('CSC', '8260', 'Advanced Image Processing', 4),
('CSC', '8270', 'Digital Signal Processing', 4),
('CSC', '8320', 'Advanced Operating Systems', 4),
('CSC', '8321', 'Multimedia Systems', 4),
('CSC', '8350', 'Advanced Software Engineering', 4),
('CSC', '8370', 'Data Security', 4),
('CSC', '8520', 'Applied Combinatorics and Graph Theory', 4),
('CSC', '8530', 'Parallel Algorithms', 4),
('CSC', '8540', 'Advanced Algorithms in Bioinformatics', 4),
('CSC', '8550', 'Advanced Algorithms with Applications to Networks', 4),
('CSC', '8560', 'Discrete Approximation Algorithms and Metaheuristics', 4),
('CSC', '8610', 'Advanced Numerical Analysis', 4),
('CSC', '8620', 'Numerical Linear Algebra', 4),
('CSC', '8630', 'Advanced Bioinformatics', 4),
('CSC', '8710', 'Deductive Databases and Logic Programming', 4),
('CSC', '8711', 'Databases and the Web', 4),
('CSC', '8712', 'Advanced Database Systems', 4),
('CSC', '8713', 'Spatial and Scientific Databases', 4),
('CSC', '8720', 'Advanced Human-Computer Interaction', 4),
('CSC', '8740', 'Advanced Data Mining', 4),
('CSC', '8741', 'Graph Mining', 4),
('CSC', '8810', 'Computational Intelligence', 4),
('CSC', '8820', 'Advanced Graphics Algorithms', 4),
('CSC', '8830', 'Computer Vision: Theory and Systems', 4),
('CSC', '8840', 'Modeling and Simulation Theory and Application', 4),
('CSC', '8850', 'Advanced Machine Learning', 4),
('CSC', '8851', 'Deep Learning', 4),
('CSC', '8852', 'Advanced Topics of Deep Learning', 4),
('CSC', '8900', 'Seminar in Computer Science', 1),
('CSC', '8901', 'Perspectives in Computer Science', 1),
('CSC', '8902', 'Ethics for Data Science', 4),
('CSC', '8910', 'Computer Science Topics Seminar', 0),
('CSC', '8920', 'Computer Science Teaching Pedagogy', 4),
('CSC', '8930', 'MS Project', 0),
('CSC', '8940', 'Computer Science Internship', 0),
('CSC', '8950', 'Directed Research in Computer Science', 0),
('CSC', '8980', 'Topics in Computer Science', 4),
('CSC', '8981', 'Research in Computer Science', 0),
('CSC', '8982', 'Lab in Computer Science', 0),
('CSC', '8999', 'Thesis Research', 0),
('CSC', '9900', 'Seminar in Computer Science', 0),
('CSC', '9999', 'Doctoral Dissertation Research', 0);